title: Портфолио Орлова Валентина
email: orlovv@herzen.spb.ru
description: >
  description
baseurl: "/portfolio"
url: "/portfolio"
github_username:  xunto

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
